/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_mao_jpeg_Utils */

#ifndef _Included_com_aspire_mao_ImageToolKit
#define _Included_com_aspire_mao_ImageToolKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aspire_mao_ImageToolKit
 * Method:    resize
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aspirecn_hawaii_image_ImageToolKit_resize
(JNIEnv *, jclass, jbyteArray, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
