/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "resize.h"
#include "string.h"
/* Header for class com_mao_jpeg_Utils */
//com.aspirecn.hawaii
#ifndef _Included_com_aspire_mao_ImageToolKit
#define _Included_com_aspire_mao_ImageToolKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mao_jpeg_Utils
 * Method:    resizeJPEG
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aspirecn_hawaii_image_ImageToolKit_resize
(JNIEnv *env, jclass cls, jbyteArray array, jint size, jint quality) {
	if ((array == NULL) || size == 0 || quality <= 0 || quality > 100)
		return NULL;

	jboolean iscopy = JNI_FALSE;
	jbyte* src = (*env)->GetByteArrayElements(env, array, &iscopy);
	if ( !src )
		return NULL;
	
	jsize src_size = (*env)->GetArrayLength(env, array);

	jsize dst_size = 0;
	jbyte* dst = (jbyte *)aspire_mao_resize_image((unsigned int *)&dst_size, (unsigned char*)src, (unsigned int)src_size, (int)size, (int)quality);
	(*env)->ReleaseByteArrayElements(env, array, src, 0);

	if (!dst || !dst_size)
		return NULL;
	
	jbyteArray out_array = (*env)->NewByteArray(env, dst_size);
	(*env)->SetByteArrayRegion( env, out_array, 0, dst_size, dst );
	free(dst);
	
	return out_array;
}


#ifdef __cplusplus
}
#endif
#endif
