/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include "rwjpg.h"
#include "rwpng.h"
#include "oprgb.h"
/* Header for class com_mao_jpeg_Utils */
//com.aspirecn.hawaii
#ifndef _Included_com_aspire_mao_ImageToolKit
#define _Included_com_aspire_mao_ImageToolKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mao_jpeg_Utils
 * Method:    resizeJPEG
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aspirecn_hawaii_image_ImageToolKit_resize
(JNIEnv *env, jclass cls, jbyteArray array, jint size, jint quality) {
	if ((array == NULL) || size == 0 || quality <= 0 || quality > 100)
		return NULL;

	jboolean iscopy = JNI_FALSE;
	jbyte* src = (*env)->GetByteArrayElements(env, array, &iscopy);
	if ( !src )
		return NULL;
	
	jsize src_size = (*env)->GetArrayLength(env, array);

	//set some vals
	int width       = 0;
	int height      = 0;
	int pixel_bytes = 3;
	int is_png      = 0;
	int is_jpg      = 0;
	unsigned char* rgb = NULL;

	//read from jpg or png
	if (aspire_mao_image_is_jpg((unsigned char*)src, src_size))
	{
		rgb = aspire_mao_jpg_read((unsigned char*)src, src_size, &width, &height);
		is_jpg = 1;
	}
	else if(aspire_mao_image_is_png((unsigned char*)src, src_size))
	{
		rgb = aspire_mao_png_read((unsigned char*)src, src_size, &width, &height, &pixel_bytes, 0);
		is_png = 1;
	}
	
	//free src bytes
	(*env)->ReleaseByteArrayElements(env, array, src, 0);
	
	
	//check rgb & width & height
	if (rgb == NULL
		|| width == 0
		|| height == 0)
		return NULL;
	
	
	//calc aspect ratio
	float ratio_w = size / (float)width;
	float ratio_h = size / (float)height;
	float ratio = ratio_w < ratio_h ? ratio_w : ratio_h;
	
	//dest size
	int dest_width = ratio * width;
	int dest_height = ratio * height;
	
	//resize rgb now.
	unsigned char* resize_rgb = aspire_mao_resize_rgb(dest_width, dest_height, rgb, width, height, pixel_bytes);
	
	//free src_rgb
	free(rgb);
	
	
	jsize dst_size = 0;
	jbyte* dst = NULL;
	if (is_jpg) {
		dst = (jbyte *)aspire_mao_jpg_write((unsigned int *)&dst_size, (unsigned char*)resize_rgb, dest_width, dest_height, quality);
	}else if (is_png) {
		dst = (jbyte *)aspire_mao_png_write((unsigned int *)&dst_size, (unsigned char*)resize_rgb, dest_width, dest_height, pixel_bytes);
	}
	
	//check dst
	if (!dst || !dst_size)
		return NULL;
	
	jbyteArray out_array = (*env)->NewByteArray(env, dst_size);
	(*env)->SetByteArrayRegion( env, out_array, 0, dst_size, dst );
	
	//free dst
	free(dst);
	
	return out_array;
}


#ifdef __cplusplus
}
#endif
#endif
