/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include "resize.h"
#include "webp2jpg.h"

/* Header for com_aspirecn_mao_ImageTools */

#ifndef _Included_com_aspirecn_mao_ImageTools
#define _Included_com_aspirecn_mao_ImageTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aspirecn_mao_ImageTools
 * Method:    resize
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aspirecn_mao_ImageTools_resize
(JNIEnv *env, jclass cls, jbyteArray array, jint size, jint quality) {
	if ((array == NULL) || size == 0 || quality <= 0 || quality > 100)
		return NULL;
	
	//create src
	jbyte* src = (*env)->GetByteArrayElements(env, array, NULL);
	if ( !src )
		return NULL;
	
	jsize src_size = (*env)->GetArrayLength(env, array);
	
	//resize native
	jsize dst_size = 0;
	jbyte* dst = (jbyte *)aspire_mao_resize_image((unsigned int *)&dst_size, (unsigned char*)src, src_size, size, quality);
	
	//release src
	(*env)->ReleaseByteArrayElements(env, array, src, 0);
	
	//check dst
	if (!dst || !dst_size)
		return NULL;
	
	jbyteArray out_array = (*env)->NewByteArray(env, dst_size);
	(*env)->SetByteArrayRegion( env, out_array, 0, dst_size, dst );
	
	//free dst
	free(dst);
	
	return out_array;
}

/*
 * Class:     com_aspirecn_mao_image_ImageTools
 * Method:    webp2jpg
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aspirecn_mao_ImageTools_webp2jpg
(JNIEnv * env, jclass cls, jbyteArray array, jint quality)
{
	if (array == NULL)
		return NULL;
	
	//create src
	jbyte* src = (*env)->GetByteArrayElements(env, array, NULL);
	if ( !src )
		return NULL;
	
	jsize src_size = (*env)->GetArrayLength(env, array);
	
	//resize native
	jsize dst_size = 0;
	jbyte* dst = (jbyte *)aspire_mao_webp_to_jpg((unsigned int *)&dst_size, (unsigned char*)src, src_size, quality);
	
	//release src
	(*env)->ReleaseByteArrayElements(env, array, src, 0);
	
	//check dst
	if (!dst || !dst_size)
		return NULL;
	
	jbyteArray out_array = (*env)->NewByteArray(env, dst_size);
	(*env)->SetByteArrayRegion( env, out_array, 0, dst_size, dst );
	
	//free dst
	free(dst);
	
	return out_array;
}


#ifdef __cplusplus
}
#endif
#endif
