/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aspirecn_mao_ImageTools */

#ifndef _Included_com_aspirecn_mao_ImageTools
#define _Included_com_aspirecn_mao_ImageTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aspirecn_mao_ImageTools
 * Method:    resize
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aspirecn_mao_ImageTools_resize
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_aspirecn_mao_ImageTools
 * Method:    webp2jpg
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aspirecn_mao_ImageTools_webp2jpg
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
